## import torch
- 새로운 env 생성
    - conda create -y -n torch_env ipykernel python=3.6
    - activate torch_env
    - conda install pytorch=0.4.1 cuda90 -c pytorch
    


In [1]:
import numpy as np
import torch

In [2]:
t = np.array([[1., 2., 3.], [3., 4., 5., 6.]])
print(t)

[list([1.0, 2.0, 3.0]) list([3.0, 4.0, 5.0, 6.0])]


In [3]:
print(f'Rank of t : {t.ndim}')
print(f'Shape of t : {t.shape}')

Rank of t : 1
Shape of t : (2,)


In [3]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])

In [10]:
print(type(t))
print(t.dim())
print(t.shape)
print(t[0])
print(t[0:3])

<class 'torch.Tensor'>
1
torch.Size([7])
tensor(0.)
tensor([0., 1., 2.])


In [11]:
t = torch.FloatTensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                      ])

In [20]:
print(type(t))
print(t.dim())
print(t.size())
print(t.shape)
print(t[:,1].size())

<class 'torch.Tensor'>
2
torch.Size([3, 3])
torch.Size([3, 3])
torch.Size([3])


## Broadcasting
> matrix간의 연산에 필요한 규칙으로 자동적으로 맞춰 줌

### same shape

In [24]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1.shape, m2.shape)
print(m1 + m2)

torch.Size([1, 2]) torch.Size([1, 2])
tensor([[5., 5.]])


### vecor + scalar
- 벡터 값에 맞게 자동으로 변환되어 연산을 가능하게 함

In [26]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1.shape, m2.shape)
print(m1 + m2)

torch.Size([1, 2]) torch.Size([1])
tensor([[4., 5.]])


### 2x1 vector + 1x2 vector

In [28]:
m1 = torch.FloatTensor([[1,2]]) 
m2 = torch.FloatTensor([[3],[4]])
print(m1.shape, m2.shape)
print(m1 + m2)

torch.Size([1, 2]) torch.Size([2, 1])
tensor([[4., 5.],
        [5., 6.]])


### broad casting은 자동적으로 실행되기때문에 디버깅에 어려움

In [33]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.shape)
print(m2.shape)
print(m1 * m2) # m1.mal(m2) , borad casting이 적용되어 연산
print(m1.matmul(m2)) # 행렬 간 곱 연산

torch.Size([2, 2])
torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[ 5.],
        [11.]])


### Mean

In [34]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [35]:
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [36]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [39]:
print(t.mean())
print(t.mean(dim=0)) # axis 고려한 mean 연산
print(t.mean(dim=1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


### Sum

In [40]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [41]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


### Max and Argmax

In [42]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [44]:
print(t.max())
print(t.max(dim = 0)) # argmax인 index 값을 같이 리턴 해줌

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [48]:
print(t.max(dim = 0)[0]) # max
print(t.max(dim = 0)[1]) # argmax

tensor([3., 4.])
tensor([1, 1])


In [50]:
print(t.max(dim = 1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### View(Reshape)

In [52]:
t = np.array(
    [
        [[0,1,2],
         [3,4,5]
        ],
        [[6,7,8],
         [9,10,11]
        ],
    ]
)
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [57]:
# 맨 마지막 shape을 3으로만 맞추고 나머지는 알아서
print(ft.view(-1,3))
print((ft.view(-1,3)).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [58]:
# 맨 마지막 shape을 (1,3)으로 맞추고 나머지는 알아서
print(ft.view(-1,1,3))
print((ft.view(-1,1,3)).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze
- view와 비슷한데 자동적으로 1인 dimension을 없애 줌

In [59]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [61]:
print(ft.squeeze())
print(ft.squeeze().shape)
# squeeze에 인자를 주게되면 해당 axis가 1이면 squeeze를 해줌

tensor([0., 1., 2.])
torch.Size([3])


### unsqueeze
- 해당 axis를 1-dimension으로

In [64]:
ft = torch.Tensor([0,1,2])
print(ft.shape)
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [66]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [67]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type Casting

In [68]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [70]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [71]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [74]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate

In [78]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

In [81]:
# dimension을 기준으로 concat
print(torch.cat([x,y], dim =0))
print(torch.cat([x,y], dim =1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking
- concatenateion을 좀더 편리하게 사용할 수 있게 단축시켜놓음
- dimension을 기준으로 그냥 쌓는걸로 생각하면 될듯

In [2]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 8])
print(x.shape)

torch.Size([2])


In [84]:
# default dimension은 0
print(torch.stack([x, y, z])) # [2,]
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 8.]])
tensor([[1., 2., 3.],
        [4., 5., 8.]])


In [5]:
x.shape

torch.Size([2])

In [4]:
x.unsqueeze(0).shape

torch.Size([1, 2])

In [7]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 8.]])


### Ones and Zeros

In [8]:
x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [9]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-placev Operation
- `_`를 추가함으로써 리턴되는 결과값을 인자에 다시 넣어줌

In [16]:
x = torch.FloatTensor([[1,2], [3,4]])

In [17]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
