# [Pytorch 패키치 소개](https://datascienceschool.net/view-notebook/4f3606fd839f4320a4120a56eec1e228/)
> GPU 연산 지원하는 딥러닝 프레임워크

## conda install
- https://pytorch.org/get-started/locally/

```bash
conda install pytorch torchvision cudatoolkit=9.2 -c pytorch -c defaults -c numba/label/dev
```


In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
torch.__version__

'1.2.0'

## 텐서 자료형
> Pytorch의 텐서 자료형은 Numpy의 배열과 유사한 자료형

- 텐서 자료형을 사용하는 방법도 Numpy와 유사
    - 리스트나 Numpy 배열을 텐서로 변환
    - 0 또는 1 등의 특정한 값을 가진 텐서를 생성
    - 랜덤한 값을 가지는 텐서를 생성

### 배열과 리스트를 텐서 자료형으로 변환
- 리스트를 텐서 자료형으로 바꾸려면 `torch.tensor()` 또는 `torch.as_tensor()`, `torch.from_numpy()` 명령 사용
    - `torch.tensor()` : 값 복사를 사용하여 새로운 텐서 자료형 인스턴스 생성
    - `torch.as_tensor()` : 리스트나 ndarray 객체를 받음, 값 참조를 사용하여 텐서 자료형 뷰를 만듬
    - `torch.from_numpy()` : ndarray 객체를 받음, 값 참조를 사용하여 텐서 자료형 뷰를 만듬

In [3]:
li = np.array([[1,2], [3, 4]])

li_tensor = torch.tensor(li)
li_as_tensor = torch.as_tensor(li)

print(li_tensor)
print(li_as_tensor)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [9]:
arr = np.array([[1, 2], [3, 4]])

arr_tensor = torch.tensor(arr)
arr_as_tensor = torch.from_numpy(arr)
arr_from_numpy = torch.from_numpy(arr)

print(arr_tensor)
print(arr_as_tensor)
print(arr_from_numpy)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


### 텐서를 numpy로 바꿀 때는 `torch.numpy()`

In [11]:
tensor_to_numpy = arr_tensor.numpy()
print(tensor_to_numpy, type(tensor_to_numpy))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


### `torch.as_tensor()`나 `torch.from_numpy()`는 값을 참조하기 때문에 값을 바꾸거나 참조하던 ndarray객체 값이 바뀌면 같이 바뀜

In [14]:
arr_as_tensor[0 ,0] = 1000
print(f'원본 : {arr}')
print(f'참조하던 tensor : {arr_as_tensor}')

원본 : [[1000    2]
 [   3    4]]
참조하던 tensor : tensor([[1000,    2],
        [   3,    4]], dtype=torch.int32)


In [17]:
arr_from_numpy[0, 1] = 2000
print(f'원본 : {arr}')
print(f'참조하던 tensor : {arr_from_numpy}')

원본 : [[1000 2000]
 [   3    4]]
참조하던 tensor : tensor([[1000, 2000],
        [   3,    4]], dtype=torch.int32)


## 랜덤한 값을 가지는 텐서 생성
- `torch.rand()` : 0과 1사이 숫자를 균등하게 생성
- `torch.randd_like()` : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
- `torch.randn()` : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 생성
- `torch.randn_like()` : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
- `torch.randint()` : 주어진 범위 내의 점수 균등생성
- `torch.randint_like()` : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
- `torch.randperm()` : 주어진 범위 내의 정수를 랜덤하게 생성
- `torch.manul_seed()` : 시드 설정

In [18]:
torch.manual_seed(0)

a = torch.rand(5)
b = torch.randn(5)
c = torch.randint(10, size=(5,))
d = torch.randperm(5)

print(a)
print(b)
print(c)
print(d)

tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074])
tensor([ 0.5507,  0.2704,  0.6472,  0.2490, -0.3354])
tensor([8, 4, 3, 6, 9])
tensor([1, 3, 4, 2, 0])


### 특정한 값으로 초기화를 하지 않는 행렬

In [29]:
torch.empty(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## 특정한 값의 텐서 생성
- `torch.arange()` : 주어진 범위 내의 정수를 순서대로 생성
- `torch.ones()` : 주어진 사이즈의 1로 이루어진 텐서 생성
- `torch.zeros()` : 주어진 사이즈의 0으로 이루어진 텐서 생성
- `torch.ones_like()` : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
- `torch.zeros_like()` : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의
- `torch.linspace()` : 시작점과 끝점을 주어진 갯수만큼 균등하게 나눈 간격점을 형벡터로 출력
- `torch.logspae()` : 시작점과 끝점을 주어진 갯수만큼 로그간격으로 나눈 간격점을 행벡터로 출력

In [30]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
torch.ones((2,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [32]:
torch.zeros((3,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [33]:
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

## 텐서 자료형 변한

In [36]:
arr_tensor.dtype

torch.int32

In [39]:
# dtype 바뀐 값 리턴, 원본은 그대로
arr_tensor.type(dtype=torch.float32)

tensor([[1., 2.],
        [3., 4.]])

## 텐서 형상 변환(reshape)
- `.view()`사용

In [44]:
t1 = torch.ones(4, 3)
t2 = t1.view(3, 4)
t3 = t1.view(12)

print(t1, t1.shape)
print(t2, t2.shape)
print(t3, t3.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.Size([4, 3])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) torch.Size([3, 4])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]) torch.Size([12])


### `squeeze()`나 `unsqueeze()`를 사용해 차원 변환
- `squeeze()` : 차원의 원소가 1인 차원을 없애고 값을 return `_`을 붙이면 자체 변수 값 수정
- `unsqueeze()` : 인수로 받은 위치에 새로운 차원을 삽입

In [55]:
t4 = torch.rand(1,3,3)
t4.shape

torch.Size([1, 3, 3])

In [56]:
t4.squeeze().shape

torch.Size([3, 3])

In [57]:
t4.shape

torch.Size([1, 3, 3])

In [58]:
t4.squeeze_()

tensor([[0.5675, 0.8352, 0.2056],
        [0.5932, 0.1123, 0.1535],
        [0.2417, 0.7262, 0.7011]])

In [59]:
t4.shape

torch.Size([3, 3])

In [61]:
t5 = torch.rand(3,3)
t5.shape

torch.Size([3, 3])

In [63]:
t5.unsqueeze(0).shape

torch.Size([1, 3, 3])

In [64]:
t5.unsqueeze(1).shape

torch.Size([3, 1, 3])

## 복수의 텐서를 결합/분할
- `torch.cat()` : 합치는 텐서를 list인자로 주고, 어느 방향으로 결합하는지 dim인자로 줌
- `torch.chunk()` : 텐서를 여러개로 나눔
- `torch.split()` : 두번째 인자를 기준으로 split

In [65]:
a = torch.ones(2, 3)
b = torch.zeros(3, 3)

torch.cat([a, b], dim=0)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [71]:
c = torch.rand(3, 6)
c1, c2, c3 = torch.chunk(c, 3, dim=1)
print(c, c.shape)
print(c1, c1.shape)
print(c2, c2.shape)
print(c3, c3.shape)

tensor([[0.8579, 0.4486, 0.5139, 0.4569, 0.6012, 0.8179],
        [0.9736, 0.8175, 0.9747, 0.4638, 0.0508, 0.2630],
        [0.8405, 0.4968, 0.2515, 0.1168, 0.0321, 0.0780]]) torch.Size([3, 6])
tensor([[0.8579, 0.4486],
        [0.9736, 0.8175],
        [0.8405, 0.4968]]) torch.Size([3, 2])
tensor([[0.5139, 0.4569],
        [0.9747, 0.4638],
        [0.2515, 0.1168]]) torch.Size([3, 2])
tensor([[0.6012, 0.8179],
        [0.0508, 0.2630],
        [0.0321, 0.0780]]) torch.Size([3, 2])


In [77]:
c1, c2 = torch.split(c, 3, dim=1)
print(c1, c1.shape)
print(c2, c2.shape)

tensor([[0.8579, 0.4486, 0.5139],
        [0.9736, 0.8175, 0.9747],
        [0.8405, 0.4968, 0.2515]]) torch.Size([3, 3])
tensor([[0.4569, 0.6012, 0.8179],
        [0.4638, 0.0508, 0.2630],
        [0.1168, 0.0321, 0.0780]]) torch.Size([3, 3])


## 텐서 연산
- 연산기호 사용하거나, torch의 함수 사용

In [82]:
x = torch.arange(0, 5)
z = torch.arange(1, 6)
print(f'x : {x} z : {z}')
print(f'x + z : {x + z}')
print(torch.add(x, z))
print(x.add(z))

x : tensor([0, 1, 2, 3, 4]) z : tensor([1, 2, 3, 4, 5])
x + z : tensor([1, 3, 5, 7, 9])
tensor([1, 3, 5, 7, 9])
tensor([1, 3, 5, 7, 9])


## 인플레이스 연산
- 명령어 뒤에 `_`을 붙이면 자기 자신의 값을 바꾸는 inplace명령이 됨, 연산 결과 반환 동시에 자기 자신의 데이터 수정

In [85]:
x = torch.arange(0, 5)
y = torch.arange(1, 6)

print(f'x : {x}')
print(f'x + z : {x.add_(z)}')
print(f'x : {x}')

x : tensor([0, 1, 2, 3, 4])
x + z : tensor([1, 3, 5, 7, 9])
x : tensor([1, 3, 5, 7, 9])


### 1개의 원소를 가진 Tensor를 Python의 Scalar로 만들 때는 `.item()` 사용

In [88]:
scl = torch.tensor(1)
print(scl)
print(scl.item())

tensor(1)
1


## GPU 사용
- GPU 연산 하기 위해선 텐서를 GPU 연산이 가능한 자료형으로 변환

In [89]:
torch.cuda.is_available()

True

### GPU 연산이 가능한 Tensor 만들기
- device 인수에 GPU 디바이스 객체를 입력하거나 문자열을 입력
- `torch.device("cuda:0")`로 생성

In [91]:
device = torch.device("cuda:0")
device

device(type='cuda', index=0)

In [93]:
ts = torch.rand(3, 3, device=device)
ts

tensor([[0.9722, 0.7910, 0.4690],
        [0.3300, 0.3345, 0.3783],
        [0.7640, 0.6405, 0.1103]], device='cuda:0')

In [95]:
ts = torch.rand(3, 3, device="cuda:0")
ts

tensor([[0.0194, 0.7733, 0.8650],
        [0.8097, 0.6666, 0.3653],
        [0.3637, 0.5681, 0.2636]], device='cuda:0')

### 기존에 있는 Tensor를 GPU 연산이 가능한 자료형으로 바꿀 때는 `.cuda()` 메서드 사용

In [103]:
cp = torch.randn(3, 3)
print(cp)
print(cp.cuda())

tensor([[-1.2535, -0.0592,  1.1878],
        [ 1.2247, -0.8521, -1.1941],
        [ 1.1076,  0.6578, -0.0423]])
tensor([[-1.2535, -0.0592,  1.1878],
        [ 1.2247, -0.8521, -1.1941],
        [ 1.1076,  0.6578, -0.0423]], device='cuda:0')


## autograd
- Pytorch에서 핵심적인 기능을 담당하는 하부 패키지
- 텐서의 연산에 대해 자동으로 미분값을 구해주는 기능을 함
- `requires_grad`인수를 True로 설정하거나 `.requires_grad_(True)`를 실행해 그 텐서에 행해지는 모든 연산에 대한 미분 값 계산
- 계산을 멈추고 싶으면 `.detach()`함수를 이용

In [104]:
x = torch.rand(2, 2, requires_grad=True)
print(x)

tensor([[0.8458, 0.1278],
        [0.7048, 0.3319]], requires_grad=True)


In [106]:
y = torch.sum(x * 3)
# y는 x연산의 결과이므로 미분 함수를 가짐
# grad_fn 통해 미분 함수 확인 가능
print(y, y.grad_fn)

tensor(6.0308, grad_fn=<SumBackward0>) <SumBackward0 object at 0x0000020AD906F4E0>


In [107]:
print(x.grad)

None


### `y.bacward()`함수를 실행하면 x의 미분값이 자동으로 갱신
- x의 `grad`속성을 확인하면 미분값이 들어있는 것을 확인할 수 있음
- `backward()`함수는 자동으로 미분값을 계산해 `requires_grad`인수가 True로 설정된 변수의 `grad`속성의 값을 갱신
- `retain_graph`는 미분을 연산하기 위해서 사용했던 임시 그래프를 유지 할 것인가를 설정
    - 동일한 연산에 대해 여러번 미분을 계산하기 위해 유지해줘야 함
- 미분값을 그대로 출력받아 사용하고 싶은 경우에는 `torch.autograd.grad()`함수에 출력값과 입력값을 입력하면 미분값을 출력

In [108]:
y.backward(retain_graph=True)

In [109]:
print(x.grad)

tensor([[3., 3.],
        [3., 3.]])


In [110]:
torch.autograd.grad(y, x)

(tensor([[3., 3.],
         [3., 3.]]),)

### 상황에 따라 특정 연산에는 미분값을 계산하고 싶지 않을 때
- `.detach()`함수 사용

In [113]:
y_1 = y.detach()
torch.sigmoid(y_1)

tensor(0.9976)

## Pytorch를 이용한 선형 회귀

In [116]:
from sklearn.datasets import load_boston
boston = load_boston()
df = pd.DataFrame(boston.data, columns=boston.feature_names)
df['const'] = np.ones(df.shape[0])
df.tail()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
501  0.06263  0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527  0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076  0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  const  
501     21.0  391.99   9.67    1.0  
502     21.0  396.90   9.08    1.0  
503     21.0  396.90   5.64    1.0  
504     21.0  393.45   6.48    1.0  
505     21.0  396.90   7.88    1.0

In [120]:
n,m = df.shape

X = torch.tensor(df.values)
y = torch.tensor(boston.target).view(-1, 1)

XT = torch.transpose(X, 0, 1)
w = torch.matmul(torch.matmul(torch.inverse(torch.matmul(XT, X)), XT), y)
y_pred = torch.matmul(X, w)

print(f'예측 집 값 : {y_pred[19]}, 실제 집값 : {boston.target[19]}')

예측 집 값 : tensor([18.4061], dtype=torch.float64), 실제 집값 : 18.2


## Pytorch를 이용한 퍼셉트론 구현

In [127]:
from sklearn.datasets import load_iris

iris = load_iris()

idx = np.in1d(iris.target, [0, 2])
x = torch.from_numpy(iris.data[idx, 0:2]).type(torch.float64)
y = torch.from_numpy((iris.target[idx] - 1.0)[:, np.newaxis]).type(torch.float64)

In [129]:
x.shape

torch.Size([100, 2])

In [130]:
y.shape

torch.Size([100, 1])

In [132]:
w = torch.rand((2,1), dtype=torch.float64, requires_grad=True)
b = torch.rand((1,1), dtype=torch.float64, requires_grad=True)

### 변수에 연산,할당을 하고 싶을 때는 변수의 data 속성을 불러와 변경

In [135]:
w.data *= 0.001
b.data *= 0.001

### SGD 최적화 수행
- `.backward()`를 사용하면 미분값이 계속 누적
- 학습한 뒤 가중치를 수정, 수정한 가중치에 대한 미분값으로 다시 학습하기 때문에 가중치를 수정한 뒤에 `.grad_zer_()`함수를 호출하여 변수에 할당된 미분값을 0으로 만들어 줌

In [139]:
learnig_rate = 0.0001
epochs = 300

for epoch in range(epochs):
    z = (x.mm(w) + b).tanh()
    loss_vec = torch.mul(-y, z)
    loss = torch.sum(torch.max(torch.cat([torch.zeros_like(loss_vec), loss_vec], dim=-1), dim=-1)[0], dim=-1)
    loss.backward()
    w.data -= w.grad * learnig_rate
    b.data -= b.grad * learnig_rate
    
    if epoch % 40 == 0:
        print(f'{epoch} - loss : {loss.item()}')
    w.grad.zero_()
    b.grad.zero_()

0 - loss : 10.255167579625489
40 - loss : 2.1622190218221022
80 - loss : 0.014426213091849577
120 - loss : 0.013727559670846202
160 - loss : 0.013029410669724665
200 - loss : 0.013308629984686314
240 - loss : 0.01306254195886122
280 - loss : 0.012365542757194413
