# MultiVariable LinearRegression
- Linear Regression
    - 1. Hypothesis
        - H(x) = Wx + b
    - 2. Cost function
        - cost(W,b) = tf.reduce_mean(tf.square(H(x)-y))
            - 예측값과 실제값의 차이 제곱의 평균
    - 3. Gradient descent algorithm
        - cost가 최소값이 되는 부분
            - W = W - (cost를 w로 미분)
- 1. Hypothesis
    - H(x1,x2,x3) = w1x1 + w2x2 + w3x3
    - using matrix 

![image](https://user-images.githubusercontent.com/28910538/53856761-c4fec580-4016-11e9-95a0-f04fe8cbb4aa.png)

![image](https://user-images.githubusercontent.com/28910538/53865761-4bc19b80-4033-11e9-8836-352f2f9908f3.png)


In [7]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 500 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  99262.97 
Prediction:
 [-134.05586 -147.11923 -152.19379 -166.32718 -108.10003]
500 Cost:  15.32958 
Prediction:
 [146.27509 188.29591 179.08748 194.34784 147.42659]
1000 Cost:  11.748597 
Prediction:
 [146.97838 187.81299 179.30196 194.51079 146.78627]
1500 Cost:  9.017145 
Prediction:
 [147.59213 187.39145 179.489   194.65382 146.2266 ]
2000 Cost:  6.9335527 
Prediction:
 [148.12772 187.0235  179.65211 194.77942 145.73735]


In [17]:
import tensorflow as tf
import numpy as np

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]
y_data = np.array(y_data).reshape(-1,1)
x_data = np.vstack((x1_data,x2_data,x3_data))
x_data = np.transpose(x_data)
print("x_data shape : {}, y_data shape : {}".format(x_data.shape, y_data.shape))

X = tf.placeholder(shape = [None, 3], dtype = tf.float32)
Y = tf.placeholder(shape = [None, 1], dtype = tf.float32)

#W = tf.get_variable("weight", shape = [3,1], initializer=tf.contrib.layers.xavier_initializer())
W = tf.Variable(tf.random_normal([3,1]),dtype = tf.float32, name = "weight")
b = tf.Variable(tf.random_normal([1]),dtype = tf.float32,name = "bias")

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis-Y))

optimize = tf.train.GradientDescentOptimizer(learning_rate=0.00001)
train = optimize.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(3000):
    _, cost_val = sess.run([train, cost], feed_dict={X:x_data, Y:y_data})
    if step % 500 == 0:
        print("cost val : {}".format(cost_val))


x_data shape : (5, 3), y_data shape : (5, 1)
cost val : 49360.0078125
cost val : 3.5923104286193848
cost val : 3.0280368328094482
cost val : 2.591874122619629
cost val : 2.2535483837127686
cost val : 1.9899667501449585


### read to csv

In [20]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import warnings

warnings.filterwarnings(action="ignore")

score_csv = pd.read_csv("./data/data-01-test-score.csv", sep=",", header=None)

x_data = score_csv[[0,1,2]].values
y_data = score_csv[3].values
y_data = y_data.reshape(-1,1)
scaler = MinMaxScaler()
x_data = scaler.fit_transform(x_data)
y_data = scaler.fit_transform(y_data)
print("x_data.shape : {}, y_data.shape : {}".format(x_data.shape, y_data.shape))

X = tf.placeholder(shape = [None, 3], dtype = tf.float32)
Y = tf.placeholder(shape = [None, 1], dtype = tf.float32)

W = tf.Variable(tf.random_normal([3,1]), dtype = tf.float32)
b = tf.Variable(tf.random_normal([1]), dtype = tf.float32)

hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis-Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2000):
    _, cost_val = sess.run([train, cost], feed_dict={X:x_data, Y:y_data})
    if step % 500 == 0:
        print("cost value : {}".format(cost_val))

        

x_data.shape : (25, 3), y_data.shape : (25, 1)
cost value : 4.412680149078369
cost value : 0.028226913884282112
cost value : 0.009903226979076862
cost value : 0.005220097955316305


### Queue Runners
- 파일들을 어떤 batch만큼 읽어오는
    - 1. tf.train.string_input_producer
    - 2. tf.TextLineReadere()
        - reader.read
    - 3. tf.decode_csv()